// Mocks generated by Mockito 5.4.6 from annotations
// in vinas_mobile/test/pages/gallery/catalogo_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vinas_mobile/core/api_client.dart' as _i2;
import 'package:vinas_mobile/core/models/coleccion_model.dart' as _i6;
import 'package:vinas_mobile/core/models/prediction_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> ping() => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getVariedades() => (super.noSuchMethod(
        Invocation.method(
          #getVariedades,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<_i4.PredictionModel>> predictImage(_i5.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictImage,
          [file],
        ),
        returnValue: _i3.Future<List<_i4.PredictionModel>>.value(
            <_i4.PredictionModel>[]),
      ) as _i3.Future<List<_i4.PredictionModel>>);

  @override
  _i3.Future<void> saveToCollection({
    required _i5.XFile? imageFile,
    required String? nombreVariedad,
    String? notas,
    double? lat,
    double? lon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToCollection,
          [],
          {
            #imageFile: imageFile,
            #nombreVariedad: nombreVariedad,
            #notas: notas,
            #lat: lat,
            #lon: lon,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<List<dynamic>> getUserCollection() => (super.noSuchMethod(
        Invocation.method(
          #getUserCollection,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<void> updateCollectionItem(
    int? idColeccion,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCollectionItem,
          [
            idColeccion,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCollectionItem(int? idColeccion) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCollectionItem,
          [idColeccion],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<dynamic>> getPublicaciones() => (super.noSuchMethod(
        Invocation.method(
          #getPublicaciones,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<dynamic>> getUserPublicaciones() => (super.noSuchMethod(
        Invocation.method(
          #getUserPublicaciones,
          [],
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  /*@override
  _i3.Future<void> createPublicacion(
      String? titulo,
      String? texto,
    ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPublicacion,
          [
            titulo,
            texto,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);*/

  @override
  _i3.Future<void> deletePublicacion(int? idPublicacion) => (super.noSuchMethod(
        Invocation.method(
          #deletePublicacion,
          [idPublicacion],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.ColeccionModel>> getCollection() => (super.noSuchMethod(
        Invocation.method(
          #getCollection,
          [],
        ),
        returnValue:
            _i3.Future<List<_i6.ColeccionModel>>.value(<_i6.ColeccionModel>[]),
      ) as _i3.Future<List<_i6.ColeccionModel>>);

  @override
  _i3.Future<bool> getTutorialStatus() => (super.noSuchMethod(
        Invocation.method(
          #getTutorialStatus,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> markTutorialAsComplete() => (super.noSuchMethod(
        Invocation.method(
          #markTutorialAsComplete,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
