"""Add cascade delete to coleccion

Revision ID: 0a0ae6034d6f
Revises: 6125a79e9c1d
Create Date: 2025-11-25 00:29:51.189369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0ae6034d6f'
down_revision: Union[str, Sequence[str], None] = '6125a79e9c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
