"""Add notas lat lon and comentarios

Revision ID: 59eea8a79bb1
Revises: cc2bb129a5a1
Create Date: 2025-11-18 12:07:54.927625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59eea8a79bb1'
down_revision: Union[str, Sequence[str], None] = 'cc2bb129a5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha_comentario', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_padre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_padre'], ['Comentarios.id_comentario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_publicacion'], ['Publicaciones.id_publicacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_index(op.f('ix_Comentarios_id_comentario'), 'Comentarios', ['id_comentario'], unique=False)
    op.add_column('Coleccion', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('Coleccion', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('Coleccion', sa.Column('longitud', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Coleccion', 'longitud')
    op.drop_column('Coleccion', 'latitud')
    op.drop_column('Coleccion', 'notas')
    op.drop_index(op.f('ix_Comentarios_id_comentario'), table_name='Comentarios')
    op.drop_table('Comentarios')
    # ### end Alembic commands ###
