"""Añadir color y morfologia

Revision ID: 6125a79e9c1d
Revises: 6816eddcbe6b
Create Date: 2025-11-24 23:32:31.996188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6125a79e9c1d'
down_revision: Union[str, Sequence[str], None] = '6816eddcbe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('ubicacion', sa.String(length=255), nullable=True))
    op.add_column('Variedades', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('Variedades', sa.Column('morfologia', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Variedades', 'morfologia')
    op.drop_column('Variedades', 'color')
    op.drop_column('Usuarios', 'ubicacion')
    # ### end Alembic commands ###
