"""Add ubicacion color and morfologia

Revision ID: 6816eddcbe6b
Revises: 59eea8a79bb1
Create Date: 2025-11-24 20:58:04.804789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6816eddcbe6b'
down_revision: Union[str, Sequence[str], None] = '59eea8a79bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
