"""Add likes, tutorial and publicacion varieties

Revision ID: 690a50936b9a
Revises: 0a0ae6034d6f
Create Date: 2025-12-05 16:49:26.047412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690a50936b9a'
down_revision: Union[str, Sequence[str], None] = '0a0ae6034d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
