"""Añadir likes, tutorial and publicacion varieties

Revision ID: 78c80f2416c9
Revises: 690a50936b9a
Create Date: 2025-12-05 16:57:11.304721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c80f2416c9'
down_revision: Union[str, Sequence[str], None] = '690a50936b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacion_variedad',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_variedad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['Publicaciones.id_publicacion'], ),
    sa.ForeignKeyConstraint(['id_variedad'], ['Variedades.id_variedad'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_variedad')
    )
    op.add_column('Comentarios', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('Publicaciones', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('Usuarios', sa.Column('tutorial_superado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'tutorial_superado')
    op.drop_column('Publicaciones', 'likes')
    op.drop_column('Comentarios', 'likes')
    op.drop_table('publicacion_variedad')
    # ### end Alembic commands ###
