"""Creacion inicial de tablas

Revision ID: cc2bb129a5a1
Revises: 
Create Date: 2025-11-16 17:46:27.527892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc2bb129a5a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('es_premium', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_Usuarios_id_usuario'), 'Usuarios', ['id_usuario'], unique=False)
    op.create_table('Variedades',
    sa.Column('id_variedad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('links_imagenes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('info_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id_variedad')
    )
    op.create_index(op.f('ix_Variedades_id_variedad'), 'Variedades', ['id_variedad'], unique=False)
    op.create_index(op.f('ix_Variedades_nombre'), 'Variedades', ['nombre'], unique=False)
    op.create_table('Coleccion',
    sa.Column('id_coleccion', sa.Integer(), nullable=False),
    sa.Column('path_foto_usuario', sa.String(length=512), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_variedad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_variedad'], ['Variedades.id_variedad'], ),
    sa.PrimaryKeyConstraint('id_coleccion')
    )
    op.create_index(op.f('ix_Coleccion_id_coleccion'), 'Coleccion', ['id_coleccion'], unique=False)
    op.create_table('Publicaciones',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('links_fotos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_index(op.f('ix_Publicaciones_id_publicacion'), 'Publicaciones', ['id_publicacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Publicaciones_id_publicacion'), table_name='Publicaciones')
    op.drop_table('Publicaciones')
    op.drop_index(op.f('ix_Coleccion_id_coleccion'), table_name='Coleccion')
    op.drop_table('Coleccion')
    op.drop_index(op.f('ix_Variedades_nombre'), table_name='Variedades')
    op.drop_index(op.f('ix_Variedades_id_variedad'), table_name='Variedades')
    op.drop_table('Variedades')
    op.drop_index(op.f('ix_Usuarios_id_usuario'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###
