"""Likes, favoritos y foto de usuario

Revision ID: d4a5c3cb051f
Revises: 7a762adda4d8
Create Date: 2025-12-11 00:36:30.838607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a5c3cb051f'
down_revision: Union[str, Sequence[str], None] = '7a762adda4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_variedad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_variedad'], ['Variedades.id_variedad'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_variedad')
    )
    op.create_table('VotosPublicacion',
    sa.Column('id_voto', sa.Integer(), nullable=False),
    sa.Column('es_like', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['Publicaciones.id_publicacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_voto'),
    sa.UniqueConstraint('id_usuario', 'id_publicacion', name='unique_voto_pub')
    )
    op.create_index(op.f('ix_VotosPublicacion_id_voto'), 'VotosPublicacion', ['id_voto'], unique=False)
    op.create_table('VotosComentario',
    sa.Column('id_voto', sa.Integer(), nullable=False),
    sa.Column('es_like', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_comentario'], ['Comentarios.id_comentario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_voto'),
    sa.UniqueConstraint('id_usuario', 'id_comentario', name='unique_voto_com')
    )
    op.create_index(op.f('ix_VotosComentario_id_voto'), 'VotosComentario', ['id_voto'], unique=False)
    op.add_column('Usuarios', sa.Column('path_foto_perfil', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuarios', 'path_foto_perfil')
    op.drop_index(op.f('ix_VotosComentario_id_voto'), table_name='VotosComentario')
    op.drop_table('VotosComentario')
    op.drop_index(op.f('ix_VotosPublicacion_id_voto'), table_name='VotosPublicacion')
    op.drop_table('VotosPublicacion')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
